### PR TITLE
New data format

### PR DESCRIPTION
**Pull request by micbar**
## Description
First attempt on new Data Format

## Related Issue
https://github.com/owncloud/data_exporter/issues/77#issuecomment-50758206

## Motivation and Context
- Introducing streamed json files (*.jsonl)
- Better Handling of large instances.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Current Format
`php occ instance:export:user someUser /tmp`
```
# tree someuser
someuser
├── files
│   ├── files
│   │   ├── someFile.txt
│   │   └── someFolder
│   │       └── anotherFile.txt
│   ├── files_trashbin
│   │   ├── files
│   │   │   └── deleted.txt.d1565074252
│   │   ├── keys
│   │   └── versions
│   └── files_versions
│       └── someFolder
│           ├── anotherFile.txt.v1565074194
│           ├── anotherFile.txt.v1565074215
│           ├── anotherFile.txt.v1565074216
│           ├── anotherFile.txt.v1565074218
│           ├── anotherFile.txt.v1565074219
│           ├── anotherFile.txt.v1565074220
│           ├── anotherFile.txt.v1565074221
│           ├── anotherFile.txt.v1565074222
│           ├── anotherFile.txt.v1565074223
│           └── anotherFile.txt.v1565074224
├── files.jsonl
├── shares.jsonl
└── user.json

9 directories, 16 files
```
### files.jsonl (prettyfied)
```
{
  "type": "folder",
  "path": "/files",
  "eTag": "5d49234cc58d8",
  "permissions": 31,
  "mtime": 1565074252
}
{
  "type": "file",
  "path": "/files/someFile.txt",
  "eTag": "2ecd8be94415b7330c34cf3b7598006d",
  "permissions": 27,
  "mtime": 1565074170
}
{
  "type": "folder",
  "path": "/files/someFolder",
  "eTag": "5d492330a970f",
  "permissions": 31,
  "mtime": 1565074224
}
{
  "type": "file",
  "path": "/files/someFolder/anotherFile.txt",
  "eTag": "e147c69432d1373ffc943c70a6dc6d01",
  "permissions": 27,
  "mtime": 1565074224
}
{
  "type": "folder",
  "path": "/files_trashbin",
  "eTag": "5d49234cc4422",
  "permissions": 31,
  "mtime": 1565074252
}
{
  "type": "folder",
  "path": "/files_trashbin/files",
  "eTag": "5d49234cc4422",
  "permissions": 31,
  "mtime": 1565074252
}
{
  "type": "file",
  "path": "/files_trashbin/files/deleted.txt.d1565074252",
  "eTag": "325681baa0768a0129414f8cd3982d61",
  "permissions": 27,
  "mtime": 1565074247
}
{
  "type": "folder",
  "path": "/files_trashbin/keys",
  "eTag": "5d4922e6d3dbf",
  "permissions": 31,
  "mtime": 1565074150
}
{
  "type": "folder",
  "path": "/files_trashbin/versions",
  "eTag": "5d4922e6d25a1",
  "permissions": 31,
  "mtime": 1565074150
}
{
  "type": "folder",
  "path": "/files_versions",
  "eTag": "5d492330a5bd4",
  "permissions": 31,
  "mtime": 1565074224
}
{
  "type": "folder",
  "path": "/files_versions/someFolder",
  "eTag": "5d492330a5bd4",
  "permissions": 31,
  "mtime": 1565074224
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074194",
  "eTag": "b19c5543bf50070bb158071dbc6ece45",
  "permissions": 27,
  "mtime": 1565074215
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074215",
  "eTag": "898d7dae7e034e9d18fc965e3e12ee83",
  "permissions": 27,
  "mtime": 1565074216
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074216",
  "eTag": "f5ef07922ed8dd24fe9c813633a30ced",
  "permissions": 27,
  "mtime": 1565074218
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074218",
  "eTag": "82f64b1e65a384a32e54723d22625cc6",
  "permissions": 27,
  "mtime": 1565074219
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074219",
  "eTag": "204194d5841e32b6f81ca17df7a3acc0",
  "permissions": 27,
  "mtime": 1565074220
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074220",
  "eTag": "14b912e5a2bca2374c8ee1d4a8cc9bcc",
  "permissions": 27,
  "mtime": 1565074221
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074221",
  "eTag": "dc6d66f6ba87f697e5680fde2ef7b73f",
  "permissions": 27,
  "mtime": 1565074222
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074222",
  "eTag": "d673e1c66c64b0660be6eafac31cd21d",
  "permissions": 27,
  "mtime": 1565074223
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074223",
  "eTag": "d5077261a68176e5fef6f69d1cc46bad",
  "permissions": 27,
  "mtime": 1565074224
}
{
  "type": "file",
  "path": "/files_versions/someFolder/anotherFile.txt.v1565074224",
  "eTag": "1c0ec99c238496d24252c88bb0b64b63",
  "permissions": 27,
  "mtime": 1565074224
}
```
### shares.jsonl (prettyfied)
```
{
  "path": "/someFile.txt",
  "shareType": "user",
  "owner": "someUser",
  "sharedBy": "someUser",
  "type": "file",
  "sharedWith": "admin",
  "permissions": 19,
  "expirationDate": null,
  "password": null,
  "name": null,
  "token": null
}
{
  "path": "/someFolder",
  "shareType": "group",
  "owner": "someUser",
  "sharedBy": "someUser",
  "type": "folder",
  "sharedWith": "admin",
  "permissions": 31,
  "expirationDate": null,
  "password": null,
  "name": null,
  "token": null
}
{
  "path": "/someFile.txt",
  "shareType": "link",
  "owner": "someUser",
  "sharedBy": "someUser",
  "type": "file",
  "sharedWith": null,
  "permissions": 1,
  "expirationDate": 1567123200,
  "password": "1|$2y$10$Tu5Z7i5SK3Ky3Jn6BR.TheC1tdtwboAyYPzVFKWsznyTZXUBGgjbS",
  "name": "Public Link",
  "token": "j8n1uZ2DaDZJjl8"
}
```

### user.json (prettyfied)
```
{
  "date": "2019-08-06T06:56:15+00:00",
  "originServer": "http://localhost/",
  "user": {
    "userId": "someUser",
    "displayName": "someUser",
    "email": null,
    "quota": "default",
    "backend": "Database",
    "enabled": true,
    "groups": [
      "people"
    ],
    "preferences": [
      {
        "appId": "core",
        "configKey": "lang",
        "configValue": "de"
      },
      {
        "appId": "core",
        "configKey": "timezone",
        "configValue": "Europe/Berlin"
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by IljaN** [comment]
We should also include an .md in docs which has examples of the jsonl files

**Comment by IljaN** [comment]
@micbar I have an somewhat similar solution prototyped which moves the responsibility of encoding jsonl-streams in to the serializer. Will provide PR for discussion shortly.

**Comment by felixboehm** [comment]
> We should also include an .md in docs which has examples of the jsonl files

yes, please.

**Comment by micbar** [comment]
@butonic @IljaN 
During testing I noticed, that etags of folders change.

We need to consider this topic in the context of OCIS

- We need a follow-up issue to export the mtime.
- Skip writing files on import

**Comment by IljaN** [comment]
@micbar Please squash away "Fix Tests" commits before merging

**Pull request merged**
