### PR TITLE
test data import/export on files_primary_s3

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description
Adds S3 as backend for unit/integration tests

## Related Issue
#27

## Motivation and Context
Test s3 

## How Has This Been Tested?
🤖 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] tests

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by patrickjahns** [comment]
@IljaN - how should we address this for acceptance tests - I believe its worthwhile for also having objecstorage tested

**Comment by phil-davis** [comment]
Integration test fail https://drone.owncloud.com/owncloud/data_exporter/433/105

**Comment by patrickjahns** [comment]
@IljaN @micbar - do you want to take over here?

**Comment by IljaN** [comment]
@patrickjahns We will, thanks :+1:

**Pull request closed without merging**
