### PR TITLE
Having a common hierarchy for the occ commands

### PR DESCRIPTION
**Pull request by mmattel**
## Description

Added a common hierarchy level for all dataexporter commands
**Before**
```
 export
  export:migrate:share                Converts the local shares pointing to the given user to federated shares pointing at the remote instance. An important prerequisite is that the user and his shares have already been imported on that remote instance
  export:user                         Exports a single user
...
 import
  import:user                         Imports a single user
```
**After**
```
dataexporter
  dataexporter:export:migrate:share   Converts the local shares pointing to the given user to federated shares pointing at the remote instance. An important prerequisite is that the user and his shares have already been imported on that remote instance
  dataexporter:export:user            Exports a single user
  dataexporter:import:user            Imports a single user
```
## Related Issue

Fixes https://github.com/owncloud/data_exporter/issues/43 (occ command naming and structure)

## Motivation and Context

Having all commands under one level

## How Has This Been Tested?

Run occ

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@pmaier1 FYI - reasonable to me - we should be a bit more clear on occ command names when initially designing new commands. THX

**Comment by IljaN** [comment]
Also other apps could extend export:* with new verbs if needed.

**Comment by DeepDiver1975** [comment]
> Also other apps could extend export:* with new verbs if needed.

export as command root is too generic in my opinion. We should really bundle commands together which really belong together. Here for me the bundling scope is the data exporter. All commands which belong together shall stay in the same scope.

I'd find is rather confusing if a e.g. office document app is adding an export command like export:office:tags - this has no relation to the data exporter and will confuse people a lot.

me can still discuss what the right root name is instead of dataexporter. It reads a bit clumsy.
instance-migration:export and instance-migration:export ? (not too sure about the dash ....)

**Comment by mmattel** [comment]
?
```
Instance
  Instance:export:migrate:share   Converts the local shares pointing to the given user to federated shares pointing at the remote instance. An important prerequisite is that the user and his shares have already been imported on that remote instance
  Instance:export:user            Exports a single user
  Instance:import:user            Imports a single user
```

**Comment by phil-davis** [comment]
I thought about:
```
data
  data:export:migrate:share   Converts the local shares pointing to the given user to federated shares pointing at the remote instance. An important prerequisite is that the user and his shares have already been imported on that remote instance
  data:export:user            Exports a single user
  data:import:user            Imports a single user
```

But looking at it, ``instance`` seems better.

**Comment by phil-davis** [comment]
I thought about:
```
data
  data:export:migrate:share   Converts the local shares pointing to the given user to federated shares pointing at the remote instance. An important prerequisite is that the user and his shares have already been imported on that remote instance
  data:export:user            Exports a single user
  data:import:user            Imports a single user
```

But looking at it, ``instance`` seems better.

**Comment by mmattel** [comment]
Implemented the changes including from #46

**Comment by pmaier1** [comment]
> @pmaier1

https://github.com/owncloud/data_exporter/pull/45#issuecomment-431854791 looks quite good! Thanks.

**Comment by mmattel** [comment]
Thanks @pmaier1 
Merging ?

**Comment by IljaN** [comment]
@mmattel We will merge this as soon as we got our first github (no-marketpalce) beta release done here.

**Comment by DeepDiver1975** [comment]
> @mmattel We will merge this as soon as we got our first github (no-marketpalce) beta release done here.

background? THX

**Comment by DeepDiver1975** [comment]
> background? THX

@IljaN

**Pull request merged**
